// Generated by CoffeeScript 1.3.3

define(function(require, exports, module) {
  var PATH_TO_COFFEE, ext, ide;
  ide = require('core/ide');
  ext = require('core/ext');
  PATH_TO_COFFEE = 'node_modules/coffee-script/bin/coffee';
  return module.exports = ext.register('ext/coffeescript/coffeescript', {
    name: 'Coffeescript',
    dev: 'Lauris Vāvere',
    type: ext.GENERAL,
    alone: true,
    hook: function() {
      var compile;
      ide.addEventListener('afterfilesave', function(e) {
        var match, node, path;
        node = e.node;
        path = node.getAttribute("path");
        match = path.match(/.coffee$/);
        if (match) {
          return compile(path);
        }
      });
      return compile = function(path) {
        return console.log('compile #{path} ...');
      };
    },
    init: function() {},
    show: function() {},
    enable: function() {},
    disable: function() {},
    destroy: function() {}
  });
});
