// Generated by CoffeeScript 1.3.3

define(function(require, exports, module) {
  var PATH_TO_COFFEE, afterFileSave, compile, enabled, ext, fs, ide, noderunner;
  ide = require('core/ide');
  ext = require('core/ext');
  noderunner = require('ext/noderunner/noderunner');
  fs = require("ext/filesystem/filesystem");
  PATH_TO_COFFEE = 'node_modules/coffee-script/bin/coffee';
  enabled = true;
  afterFileSave = function(e) {
    var match, path;
    if (enabled) {
      path = e.node.getAttribute("path");
      match = path.match(/\/src\/[^/]+\.coffee$/);
      if (match) {
        return compile(path);
      }
    }
  };
  compile = function(path) {
    var virtualCoffee;
    virtualCoffee = ide.davPrefix + "/" + PATH_TO_COFFEE;
    return fs.exists(virtualCoffee, function(exists) {
      var realPath;
      if (exists) {
        realPath = path.slice(ide.davPrefix.length + 1).replace("//", "/");
        return noderunner.run(PATH_TO_COFFEE, ['-cbo', 'lib', realPath], false);
      }
    });
  };
  return module.exports = ext.register('ext/instantcoffee/instantcoffee', {
    name: 'InstantCoffee',
    dev: 'Lauris Vāvere',
    type: ext.GENERAL,
    alone: true,
    hook: function() {
      return ide.addEventListener('afterfilesave', afterFileSave);
    },
    init: function() {},
    enable: function() {
      return enabled = true;
    },
    disable: function() {
      return enabled = false;
    },
    destroy: function() {
      return ide.removeEventListener('afterfilesave', afterFileSave);
    }
  });
});
